services:
  - type: web
    name: budget-blaze-blitz
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    staticPublishPath: staticfiles
