# Generated by Django 4.2.20 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
